### ISSUE TITLE
Way off at higher cardinalities

### ISSUE THREAD

**Issue by minaguib** [djhworld/card#1]
Given 1M unique entries, output is reasonable:
```
$ seq 1 1000000 | card
999149
```

Given 10M unique entries, it's unreasonably off:
```
$ seq 1 10000000 | card
1981685
```

Perhaps consider allowing the user to specify a size hint to tune the HLL structure more appropriately ?

**Comment by djhworld** [comment]
Hi @minaguib 

This might be a result of the `seq` command emitting scientific notation for numbers > 1,000,000

If you do 

```
$ seq -f "%.02f"  1 10000000 | card
10002989
```

It will format the number from `seq` as a float, and not convert it to scientific notation, so the items will be unique going into `card`

**Comment by minaguib** [comment]
I should have caught this earlier. Confirming:
```
$ seq 1 10000000 | tail
9.99999e+06
9.99999e+06
9.99999e+06
9.99999e+06
1e+07
1e+07
1e+07
1e+07
1e+07
1e+07
```

Thank you :)
